# Generated by Django 6.0.3 on 2026-04-05 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_level', models.FloatField()),
                ('temperature', models.FloatField()),
                ('smoke_level', models.FloatField()),
                ('gas_temp_ratio', models.FloatField(null=True)),
                ('smoke_gas_ratio', models.FloatField(null=True)),
                ('temp_smoke_interaction', models.FloatField(null=True)),
                ('combined_risk_score', models.FloatField(null=True)),
                ('prediction', models.IntegerField()),
                ('confidence_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazard_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'HazardRecords',
                'ordering': ['-created_at'],
            },
        ),
    ]
