# Generated by Django 5.2.12 on 2026-04-05 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazardrecord',
            name='combined_risk_score',
        ),
        migrations.RemoveField(
            model_name='hazardrecord',
            name='gas_temp_ratio',
        ),
        migrations.RemoveField(
            model_name='hazardrecord',
            name='smoke_gas_ratio',
        ),
        migrations.RemoveField(
            model_name='hazardrecord',
            name='temp_smoke_interaction',
        ),
        migrations.AlterField(
            model_name='hazardrecord',
            name='confidence_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='hazardrecord',
            name='gas_level',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hazardrecord',
            name='smoke_level',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hazardrecord',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hazardrecord',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='hazard_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
